<?php
//==================================
// DO NOT EDIT THIS FILE!
//==================================
// PMSFopole - DEFAULT CONFIG FILE
//==================================
if (!isset($_SESSION)) {
  session_start();
}
require_once(__DIR__ . '/../utils.php');

$libs[] = "Scanner.php";
$libs[] = "RDM.php";
$libs[] = "MAD.php";

foreach ($libs as $file) {
  include(__DIR__ . '/../lib/' . $file);
}

setSessionCsrfToken();


$enableCsrf = true;                                                 // Don't disable this unless you know why you need to :)
$sessionLifetime = 43200;                                           // Session lifetime, in seconds
$enableDebug = false;

$locale = 'en';  // Supports 'en', 'de' & 'pl'

$pageName = 'PMSFopole';
$headerName = 'PMSFopole';
$headerImage = 'static/images/headerimage.png';

$scanner = 'rdm';
